### ISSUE TITLE
[EPIC] Minimum Viable Release

### ISSUE THREAD

**Issue by pippinmole** [pippinmole/SolScanner#6]
# Required Endpoints

These endpoints need to be implemented and tested before releasing a nuget package

- [x] account transfer
- [x] account token-accounts
- [x] account defi-activities
- [x] account balance change activities
- [x] account transactions
- [x] account stake
- [x] account detail
- [ ] account rewards export
- [ ] account transfer export
- [ ] token transfer
- [ ] token defi activities
- [ ] token markets
- [ ] token list
- [ ] token trending
- [ ] token price
- [ ] token holders
- [ ] token meta
- [ ] token top
- [ ] news nft
- [ ] nft activities
- [ ] nft collection lists
- [ ] nft collection items
- [x] transaction last
- [ ] transaction detail (difficult)
- [ ] transaction actions
- [ ] block last
- [ ] block transactions
- [ ] block detail
- [ ] monitor usage
- [x] pool market list
- [x] get market info
- [x] get market volume
